### ISSUE TITLE
Running time too long

### ISSUE THREAD

**Issue by xiru-huang** [XQBai/CCNMF#1]
Hi,

I tried to apply it to a dataset that has 93 cells with scRNA-seq and 93 cells with CNV, and around 10,000 genes. I have been running CCNMF on this dataset for two weeks, but it hasn't finished yet. Is there any way to accelerate the running process? 

Thanks for your help!

**Comment by XQBai** [comment]
Hi Xiru, 

For your datasets, CCNMF supposes to finish in several minutes. Have you filtered genes?  I suggest running CCNMF after selecting the most important genes not using 10000 genes. Please let me know if you still have problems. 

Best, 
Xiangqi

**Comment by xiru-huang** [comment]
> 

Thanks for your help! I select 2000 genes, and the running time was reduced to 1 minute.

**Comment by XQBai** [comment]
Glad to hear that. Please let me know if you have further questions. 

Best, 
Xiangqi

**Comment by hfl112** [comment]
> > 
> 
> Thanks for your help! I select 2000 genes, and the running time was reduced to 1 minute.



> Hi Xiru,
> 
> For your datasets, CCNMF supposes to finish in several minutes. Have you filtered genes? I suggest running CCNMF after selecting the most important genes not using 10000 genes. Please let me know if you still have problems.
> 
> Best, Xiangqi

how about just select the top2k genes with the highest variance CNV ? or should I use the EM algorithm to select the genes
